export const SET_ITEMS = "SET_ITEMS"; // array
export const SET_PAGENUM = "SET_PAGENUM"; // number, active page
export const SET_PAGES = "SET_PAGES"; // number, total no. of pages
export const SET_TOTAL = "SET_TOTAL"; // number, total no. of items
export const SET_REFRESH = "SET_REFRESH"; // boolean, do reload page
export const SET_START = "SET_START";
export const SET_END = "SET_END";
export const SEARCH_ITEMS = "SEARCH_ITEMS";
export const DELETE_ITEM = "DELETE_ITEM";
export const ADD_ITEM = "ADD_ITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";
